[package]
name = "ox"
version = "0.1.1"
authors = ["Curly <11898833+curlpipe@users.noreply.github.com>"]
edition = "2018"

[profile.release]
lto = true

[dependencies]
termion = "1"
unicode-segmentation = "1"
unicode-width = "0"
