[package]
name = "ox"
version = "0.2.2"
authors = ["Curly <11898833+curlpipe@users.noreply.github.com>"]
edition = "2018"
description = "A Rust powered text editor."
homepage = "https://github.com/curlpipe/ox"
repository = "https://github.com/curlpipe/ox"
readme = "README.md"
include = ["src/*.rs", "Cargo.toml"]
categories = ["text-editors"]
keywords = ["text-editor", "editor", "terminal", "tui"]
license = "MIT"

[profile.release]
lto = true

[dependencies]
termion = "1.5.5"
unicode-segmentation = "1.6.0"
unicode-width = "0.1.8"
regex = "1.3.9"
signal-hook = "0.1.16"
