# Example Ox config file

[status]
# For editing the status line

# Set to true to enable the status line
enabled = true

# Format of the status line
# %f: File name
# %F: Full file name
# %t: Time (12 hour)
# %T: Time (24 hour)
# %k: File type
# %c: Cursor position
# %v: Ox version
format = "Ox: %v | %f | %k | %c"

# Powerline icons: set this to true to get powerline icons
powerline = false

[colors]
# Foreground of text
fg = "#000000"
# Background of text
bg = "#ffffff"

[startup]
# Manage the start up of Ox

# Show the welcome message on start up
welcome = true

[ide]
# For managing the IDE like features of Ox

# Assists you by suggesting possible code to insert into the line
autocomplete = true

# Automatically matches your brackets
autobracket = true

# Allows you to open other files in your project easily
filetree = true

[keys]
# For managing key bindings

  [keys.control]
  # For managing Ctrl key bindings
  c = ["copy"]
  f = ["search"]
  n = ["filetree"]
  o = ["open"]
  p = ["paste"]
  q = ["quit"]
  s = ["save"]
  w = ["save", "quit"]
  x = ["cut"]

