# My very own (awesome) Ox configuration file!
# Config name: NAME
# Author:      AUTHOR
# Year:        YEAR

[theme]
  # Holds RGB values for the theme colours

  # The background colour for the window
  bg = [41, 41, 61]

  # The default text colour
  fg = [255, 255, 255]

  # The background colour of the status bar
  status_bg = [59, 59, 84]

  # The text color of the status bar
  status_fg = [35, 240, 144]

  # For holding the text colour of the line numbers
  line_number_fg = [65, 65, 98]

[general]
  # General text editing configuraton

  # Padding to the sides of the line numbers in space characters
  line_number_padding_right = 2
  line_number_padding_left = 1

  # Tab width in space characters
  tab_width = 4

  # The seconds of inactivity before edits are placed on undo stack
  undo_period = 5

